version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin_pass
      MYSQL_DATABASE: webrotas
      MYSQL_USER: admin_webrotas
      MYSQL_PASSWORD: admin_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  flask_app:
    build: .
    restart: always
    depends_on:
      - mysql
      - redis
    environment:
      SQLALCHEMY_DATABASE_URI: "mysql://admin@webrotas:admin@pass@mysql/webrotas"
    ports:
      - "5000:5000"

volumes:
  mysql_data:
